# Generated by Django 5.0.1 on 2024-04-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_blog_likecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likepostid', models.IntegerField()),
                ('likedbyid', models.TextField()),
            ],
        ),
    ]
